LibraryCustomerSite/Models/Wishlist.cs
using System;
using System.Collections.Generic;

namespace LibraryCustomerSite.Models
{
    public partial class Wishlist
    {
        public Wishlist()
        {
            Bids = new HashSet<BookCopy>();
        }

        public int Id { get; set; }
        public int? Uid { get; set; }

        public virtual User? UidNavigation { get; set; }

        public virtual ICollection<BookCopy> Bids { get; set; }
    }
}

LibraryCustomerSite/Pages/Books/Blog.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using LibraryCustomerSite.Models;

namespace LibraryCustomerSite.Pages.Books
{
    public class BlogModel : PageModel
    {
        private readonly LMS_PRN221Context _context;

        public BlogModel(LMS_PRN221Context context)
        {
            _context = context;
        }

        public List<Blog> Blog { get; set; }

        public void OnGet()
        {
            Blog = _context.Blogs.ToList();
        }
    }
}

LibraryCustomerSite/Pages/Books/Borrow.cshtml.cs
using LibraryCustomerSite.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;

namespace LibraryCustomerSite.Pages.Books
{
    public class BorrowModel : PageModel
    {
        private readonly LMS_PRN221Context _context;
        public BorrowModel(LMS_PRN221Context context)
        {
            _context = context;
        }

        [BindProperty]
        public BorrowInformation BorrowInformation { get; set; }

        public string UserName { get; set; }
        public string Email { get; set; }
        public string BookName { get; set; }
        public IActionResult OnGet(int id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Books/SignUp");
            }

            UserName = HttpContext.Session.GetString("UserName");
            Email = HttpContext.Session.GetString("UserEmail");

            var book = _context.BookTitles.FirstOrDefault(b => b.Id == id);

            if (book == null)
            {
                return NotFound();
            }
            if (book.UnitInStock <= 0)
            {
                TempData["ErrorMessage"] = "Sách này hiện không có sẵn.";
                return RedirectToPage("/Books/Details", new { id = id });
            }
            BorrowInformation = new BorrowInformation
            {
                Uid = userId,
                BorrowDate = DateTime.Now,
                CheckoutDate = DateTime.Now,
                DueDate = DateTime.Now.AddDays(7), // Giả sử thời hạn mượn sách là 7 ngày
                Status = 2,
            };

            BookName = book.Bname;
            return Page();
        }

        public IActionResult OnPost(int id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Books/SignUp");
            }

            var book = _context.BookTitles.FirstOrDefault(b => b.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            if (book.UnitInStock <= 0)
            {
                ModelState.AddModelError(string.Empty, "Sách này hiện không có sẵn.");
                return Page();
            }

            BorrowInformation.Uid = userId;
            BorrowInformation.Status = 2; 

            // Lấy ID lớn nhất hiện có trong bảng BookCopies
            //var lastBookCopy = _context.BookCopies.OrderByDescending(bc => bc.Id).FirstOrDefault();
            //int nextIdNumber = 1;
            //if (lastBookCopy != null)
            //{
            //    // Lấy phần số từ ID cuối cùng và tăng lên 1
            //    string lastId = lastBookCopy.Id.Substring(2); // Bỏ "BC"
            //    nextIdNumber = int.Parse(lastId) + 1;
            //}
            string newId = "BC"+book.Id; // Định dạng thành "BC" + số với 3 chữ số

            // Tạo một bản sao của sách và lưu vào cơ sở dữ liệu để tạo Id
            //var bookCopy = new BookCopy
            //{
            //    Id = newId,
            //    BookTitleId = book.Id,
            //    Status = true,
            //    Note = "OK"
            //};
            var bookCopy = _context.BookCopies.Where(x=>x.Status == false).FirstOrDefault(x => x.Id.Contains(newId));
            if (bookCopy != null)
            {
                bookCopy.Status = false;
            }

            // Thêm bản sao sách vào thông tin mượn
            BorrowInformation.Bids.Add(bookCopy);
            _context.BorrowInformations.Add(BorrowInformation);

            // Giảm số lượng sách
            book.UnitInStock -= 1;
            _context.BookTitles.Update(book);

            _context.SaveChanges();

            TempData["SuccessMessage"] = "Mượn sách thành công!";
            return RedirectToPage("Index");
        }
    }
    }

LibraryCustomerSite/Pages/Books/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using LibraryCustomerSite.Models;
using Microsoft.AspNetCore.Identity;
using LibraryCustomerSite.Hubs;
using Microsoft.AspNetCore.SignalR;

namespace LibraryCustomerSite.Pages.Books
{
    public class DetailsModel : PageModel
    {
        private readonly LMS_PRN221Context _context;
        private readonly IHubContext<ServerHub> hubContext;
        public DetailsModel(LMS_PRN221Context context, IHubContext<ServerHub> hub)
        {
            _context = context;
            hubContext = hub;
        }

        [BindProperty]
        public BookTitle Book { get; set; } = default!;
        [BindProperty]
        public List<Feedback> Feedback { get; set; } = default!;
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Book = await _context.BookTitles
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Book == null)
            {
                return NotFound();
            }
            Feedback = await _context.Feedbacks
             .Where(f => f.Bid == id)
            .Include(f => f.UidNavigation)
            .ToListAsync();
            return Page();
        }
        
        public async Task<IActionResult> OnPostAddFeedbackAsync(int id, string content)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return Unauthorized();
            }

            var feedback = new Feedback
            {
                Uid = userId.Value,
                Bid = id,
                Content = content,
                CreatedDate = DateTime.Now,
                Status = true,
            };

            _context.Feedbacks.Add(feedback);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Đã thêm bình luận thành công";
            hubContext.Clients.All.SendAsync("LoadAll", id);
            return RedirectToPage(new { id = id });
        }
        public async Task<IActionResult> OnPostDeleteFeedbackAsync(int id)
        {
            var feedback = await _context.Feedbacks
                .FirstOrDefaultAsync(f => f.Id == id);

            if (feedback == null)
            {
                return NotFound();
            }

            _context.Feedbacks.Remove(feedback);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Đã xóa bình luận thành công";
            return RedirectToPage(new { id = feedback.Bid });
        }
        
        public async Task<IActionResult> OnPostAddToWishlistAsync(int id)
        {
            // Kiểm tra BookTitle có tồn tại không
            var bookTitle = await _context.BookTitles
                .FirstOrDefaultAsync(bt => bt.Id == id);

            if (bookTitle == null)
            {
                return NotFound();
            }

            // Tìm BookCopy với BookTitleId tương ứng
            var bookCopy = await _context.BookCopies
                .Include(bc => bc.BookTitle)
                .FirstOrDefaultAsync(bc => bc.BookTitleId == id);

            if (bookCopy == null)
            {
                return NotFound();
            }

            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return Unauthorized();
            }

            var wishlist = await _context.Wishlists
                .Include(w => w.Bids)
                .FirstOrDefaultAsync(w => w.Uid == userId);

            if (wishlist == null)
            {
                wishlist = new Wishlist
                {
                    Uid = userId.Value,
                    Bids = new List<BookCopy>()
                };
                _context.Wishlists.Add(wishlist);
            }

            // Kiểm tra xem sách đã tồn tại trong wishlist chưa
            if (wishlist.Bids.Any(bc => bc.Id == bookCopy.Id))
            {
                TempData["ErrorMessage"] = "Cuốn sách này đã ở trong wishlist";
                return RedirectToPage(new { id = id });
            }

            wishlist.Bids.Add(bookCopy);

            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Sách được thêm vào wishlist thành công";
            return RedirectToPage(new { id = id });
        }
        
    }
}

LibraryCustomerSite/Pages/Books/ForgotPassword.cshtml.cs
using LibraryCustomerSite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Threading.Tasks;

namespace LibraryCustomerSite.Pages.Books
{
    [AllowAnonymous]
    public class ForgotPasswordModel : PageModel
    {
        private readonly LMS_PRN221Context _context;
        private readonly IEmailSender _emailSender;

        [BindProperty]
        [Required]
        [DataType(DataType.EmailAddress)]
        public string? Email { get; set; }

        public ForgotPasswordModel(LMS_PRN221Context context, IEmailSender emailSender)
        {
            _context = context;
            _emailSender = emailSender;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _context.Users.SingleOrDefaultAsync(u => u.Email == Email);

            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Email không tồn tại");
                return Page();
            }

            // Tạo mã đặt lại mật khẩu
            var code = GeneratePasswordResetToken();
            // Lưu mã đặt lại mật khẩu vào cơ sở dữ liệu
            await SavePasswordResetToken(user.Uid, code);

            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            string link = Url.Page("/Books/ResetPassword", null, new { code = code }, Request.Scheme);

            // Gửi email
            await _emailSender.SendEmailAsync(Email, "Reset Password", $"Please reset your password by <a href='{link}'>clicking here</a>.");

            ModelState.AddModelError(string.Empty, "We've Emailed the link");
            return Page();
        }

        public void OnGet()
        {
        }

        private string GeneratePasswordResetToken()
        {
            // Tạo mã đặt lại mật khẩu (ví dụ: sử dụng GUID)
            return Guid.NewGuid().ToString();
        }

        private async Task SavePasswordResetToken(int userId, string token)
        {
            // Lưu mã đặt lại mật khẩu vào cơ sở dữ liệu
            var passwordResetToken = new PasswordResetToken
            {
                UserId = userId,
                Token = token,
                Expiration = DateTime.UtcNow.AddHours(1) // Mã hết hạn sau 1 giờ
            };
            _context.PasswordResetTokens.Add(passwordResetToken);
            await _context.SaveChangesAsync();
        }
    }
}

LibraryCustomerSite/Pages/Books/History.cshtml.cs
using LibraryCustomerSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace LibraryCustomerSite.Pages.Books
{
    public class HistoryModel : PageModel
    {
        private readonly LMS_PRN221Context _context;
        public HistoryModel(LMS_PRN221Context context)
        {
            _context = context;
        }
        public List<BorrowInformation> BorrowInformation { get; set; } = new List<BorrowInformation>();
        public string UserName { get; set; }
        public async Task<IActionResult> OnGetAsync(int id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            UserName = HttpContext.Session.GetString("UserName");
            if (userId == null || userId != id)
            {
                return RedirectToPage("/Books/SignUp");
            }

            BorrowInformation = await _context.BorrowInformations
                .Include(b => b.Bids)
                .ThenInclude(bc => bc.BookTitle)
                .Where(b => b.Uid == userId)
                .ToListAsync();

            return Page();
        }

        public IActionResult OnPostRedirectToScheduleReturn(int borrowId)
        {
            return RedirectToPage("/Books/ScheduleReturn", new { id = borrowId });
        }
    }
}

LibraryCustomerSite/Pages/Books/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using LibraryCustomerSite.Models;
using Microsoft.Data.SqlClient;

namespace LibraryCustomerSite.Pages.Books
{
    public class IndexModel : PageModel
    {
        private readonly LMS_PRN221Context _context;

        public IndexModel(LMS_PRN221Context context)
        {
            _context = context;
        }

        public IList<BookTitle> Book { get;set; } = default!;
        public IList<Category> Categories { get; set; } = new List<Category>();
        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Clear(); // Xóa toàn bộ session
            return RedirectToPage("/Books/Index"); 
        }
        public async Task OnGetAsync(List<int> categoryIds, string sortOrder)
        {
            IQueryable<BookTitle> bookQuery = _context.BookTitles
                .Where(b => b.Hide == false);

            if (categoryIds != null && categoryIds.Any())
            {
                // Lọc category được chọn
                bookQuery = bookQuery.Where(b => categoryIds.Contains(b.Cid ?? 0));
            }
            switch (sortOrder)
            {
                case "name":
                    bookQuery = bookQuery.OrderBy(b => b.Bname);
                    break;
                case "UnitInStock":
                    bookQuery = bookQuery.OrderBy(b => b.UnitInStock);
                    break;
                case "status":
                    bookQuery = bookQuery.OrderBy(b => b.Status);
                    break;
                default:
                    bookQuery = bookQuery.OrderBy(b => b.Bname); 
                    break;
            }
            Book = await bookQuery.ToListAsync();
            Categories = await _context.Categories
                .Where(c => c.Status == true)
                .ToListAsync();
        }

    }
}

LibraryCustomerSite/Pages/Books/WishList.cshtml.cs
using LibraryCustomerSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryCustomerSite.Pages.Books
{
    public class WishListModel : PageModel
    {
        private readonly LMS_PRN221Context _context;
        public WishListModel(LMS_PRN221Context context)
        {
            _context = context;
        }

        public IList<BookCopy> BookCopies { get; set; } = new List<BookCopy>();

        public async Task<IActionResult> OnGetAsync()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Books/SignUp");
            }

            var wishlist = await _context.Wishlists
                .Include(w => w.Bids)
                .ThenInclude(b => b.BookTitle)
                .Where(w => w.Uid == userId)
                .ToListAsync();

            if (wishlist != null)
            {
                BookCopies = wishlist.SelectMany(w => w.Bids).ToList();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostRemoveFromWishlistAsync(int id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return Unauthorized();
            }

            var wishlist = await _context.Wishlists
                .Include(w => w.Bids)
                .FirstOrDefaultAsync(w => w.Uid == userId);

            if (wishlist == null)
            {
                return NotFound();
            }

            var bookCopy = wishlist.Bids.FirstOrDefault(bc => bc.BookTitleId == id);
            if (bookCopy == null)
            {
                return NotFound();
            }

            wishlist.Bids.Remove(bookCopy);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Xóa thành công sách khỏi Wishlist";
            return RedirectToPage();
        }
    }
}

LibraryCustomerSite/Pages/Books/Blog.cshtml
@page
@model LibraryCustomerSite.Pages.Books.BlogModel
@{
}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Blog</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="~/css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="~/css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesoeet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
</head>
<body>
    <!-- header section start -->
    <div class="header_section">
        <div class="container-fluid header_main">
            <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:7rem">
                <a class="logo" href="/Books"><img style="width: 15%" src="~/images/logo.jpg"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/Books">Trang chủ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Books/Blog">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@(string.IsNullOrEmpty(HttpContext.Session.GetString("UserEmail")) ? "/Books/SignUp" : "/Books/WishList")">
                                WishList
                            </a>
                        </li>
                        <li class="nav-item">
                            @if (string.IsNullOrEmpty(HttpContext.Session.GetString("UserEmail")))
                            {
                                <a class="nav-link" href="/Books/SignUp">Đăng Nhập</a>
                            }
                            else
                            {
                                <form id="logoutForm" method="post" asp-page-handler="Logout" style="display: none;">
                                </form>
                                <a class="nav-link" href="javascript:void(0);" onclick="document.getElementById('logoutForm').submit();">Đăng Xuất</a>
                                @* <span>Xin chào, @HttpContext.Session.GetString("UserEmail")</span>  *@
                            }
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <!-- blog section start -->
    <div class="about_section layout_padding">
        <div class="container">
                
            <div class="row">
            @foreach(var blog in Model.Blog)
            {
                    <div class="col-lg-8 col-sm-12" style="margin-bottom: 3rem;">
                        <p class="post_text">Post By : @blog.CreatedDate</p>
                    <h2 class="most_text">@blog.Title<br>River</h2>
                    <p>@blog.Content</p>
                    <div class="social_icon_main">
                        <div class="social_icon">
                            <ul>
                                <li><a href="#"><img src="~/images/fb-icon.png"></a></li>
                                <li><a href="#"><img src="~/images/twitter-icon.png"></a></li>
                                <li><a href="#"><img src="~/images/instagram-icon.png"></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            }
                <div class="col-lg-4 col-sm-12">
                    <div class="about_main">
                        <h1 class="follow_text">CONNECT & FOLLOW</h1>
                        <div class="follow_icon">
                            <ul>
                                <li><a href="#"><img src="~/images/fb-icon-1.png"></a></li>
                                <li><a href="#"><img src="~/images/twitter-icon-1.png"></a></li>
                                <li><a href="#"><img src="~/images/linkedin-icon-1.png"></a></li>
                                <li><a href="#"><img src="~/images/instagram-icon-1.png"></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- blog section end -->
    <!-- footer section start -->
    <div class="footer_section layout_padding margin_top_90">
        <div class="container">
            <div class="footer_logo"><a href="index.html"><img src="images/footer-logo.png"></a></div>
            <div class="footer_menu">
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="features.html">Features</a></li>
                    <li><a href="contact.html">contact us</a></li>
                </ul>
            </div>
            <div class="contact_menu">
                <ul>
                    <li><a href="#"><img src="~/images/call-icon.png"></a></li>
                    <li><a href="#">Call : +01 1234567890</a></li>
                    <li><a href="blog.html"><img src="~/images/mail-icon.png"></a></li>
                    <li><a href="features.html">demo@gmail.com</a></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- footer section end -->
    <!-- copyright section start -->
    <div class="copyright_section">
        <div class="container">
            <p class="copyright_text">Copyright 2020 All Right Reserved By.<a href="https://html.design"> Free  html Templates</a></p>
        </div>
    </div>
    <!-- copyright section end -->
    <!-- Javascript files-->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-3.0.0.min.js"></script>
    <script src="~/js/plugin.js"></script>
    <!-- sidebar -->
    <script src="~/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/js/custom.js"></script>
    <!-- javascript -->
    <script src="~/js/owl.carousel.js"></script>
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
</body>
</html>

LibraryCustomerSite/Pages/Books/ForgotPassword.cshtml
@page
@model LibraryCustomerSite.Pages.Books.ForgotPasswordModel
@{
    ViewData["Title"] = "Forgot Password";
}

<h2>Forgot Password</h2>

<form method="post">
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Send Reset Link</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

LibraryCustomerSite/Pages/Books/History.cshtml
@page
@model LibraryCustomerSite.Pages.Books.HistoryModel
@{
    ViewData["Title"] = "Lịch Sử mượn";
}
<!doctype html>
<html lang="en">
<head>
    <title>Table 06</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/style1.css">
</head>
<body>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-4">
                    <h2 class="heading-section">Lịch Sử Mượn</h2>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-12">
                    <div class="table-wrap">
                        <table class="table">
                            <thead class="thead-primary">
                                <tr>
                                    <th>&nbsp;</th>
                                    <th>&nbsp;</th>
                                    <th>Tác Giả</th>
                                    <th>Ngày mượn</th>
                                    <th>Ngày trả sách</th>
                                    <th>Trạng thái</th>
                                    <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var bi in Model.BorrowInformation)
                                {
                                    <tr class="alert" role="alert">
                                        <td>
                                            <label class="checkbox-wrap checkbox-primary">
                                                <input type="checkbox" checked>
                                                <span class="checkmark"></span>
                                            </label>
                                        </td>
                                        <td>
                                            <div class="email">
                                                <span></span>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="email">
                                                <span>@Model.UserName</span>
                                            </div>
                                        </td>
                                        <td>@bi.BorrowDate</td> 
                                        <td>@bi.DueDate</td>

                                        @if (bi.ReturnDate > bi.DueDate)
                                        {
                                            <td><span style="color:red">Quá hạn</span></td>
                                            }else if(bi.ReturnDate == null)
                                        {
                                            <td><span class="">Chưa trả</span></td>
                                        }else if(bi.ReturnDate <= bi.DueDate)
                                        {
                                            <td><span class="text-success">Đã trả</span></td>
                                        }
                                        <td>
                                            <form method="post" asp-page-handler="RedirectToScheduleReturn" asp-route-borrowId="@bi.Oid">
                                                <button type="submit" class="btn btn-primary">Hẹn trả sách</button>
                                            </form>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="js/jquery.min.js"></script>
    <script src="js/popper.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/main.js"></script>
</body>
</html>

LibraryCustomerSite/Pages/Books/ResetPassword.cshtml
@page
@model LibraryCustomerSite.Pages.Books.ResetPasswordModel
@{
    ViewData["Title"] = "Reset Password";
}

<h2>Reset Password</h2>

<form method="post">
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword"></label>
        <input asp-for="ConfirmPassword" class="form-control" />
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="Code" />
    <button type="submit" class="btn btn-primary">Reset Password</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}